version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskflow
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  migrate:
    build:
      context: ..
      dockerfile: service_api/Dockerfile
    depends_on:
      - mysql
    env_file:
      - env.example
    command: ["sh", "-c", "python scripts/wait_for_db.py && alembic upgrade head"]
    restart: "no"

  api:
    build:
      context: ..
      dockerfile: service_api/Dockerfile
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    volumes:
      - /Users/sylvia/Documents/code/ai-side-project/service_api:/app/service_api
    env_file:
      - env.example
    command: [
      "uvicorn",
      "service_api.app:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload"
    ]
    ports:
      - "8000:8000"

  worker:
    build:
      context: ..
      dockerfile: service_worker/Dockerfile
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    volumes:
      - /Users/sylvia/Documents/code/ai-side-project/service_worker:/app/service_worker
    env_file:
      - env.example
    command: [
      "python",
      "-m",
      "service_worker.worker"
    ]

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    depends_on:
      api:
        condition: service_started
    environment:
      - REACT_APP_API_BASE=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000/ws
      - PORT=5001
    ports:
      - "5001:5001"

volumes:
  mysql-data:
