version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskflow
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: ..
      dockerfile: service_api/Dockerfile
    depends_on:
      - mysql
      - redis
      - rabbitmq
    env_file:
      - env.example
    ports:
      - "8000:8000"

  worker:
    build:
      context: ..
      dockerfile: service_worker/Dockerfile
    depends_on:
      - mysql
      - redis
      - rabbitmq
    env_file:
      - env.example

volumes:
  mysql-data:
